[theme]
base = "dark"
primaryColor = "#14B8A6"
backgroundColor = "#051424"
secondaryBackgroundColor = "#122131"
textColor = "#D4E4FA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
